apiVersion: v2
kind: Service
metadata:
  name: hello-world-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello-world-nginx
    spec:
      containers:
      - name: hello-world-nginx
        image: $TAGGED_IMAGE_NAME
        ports:
        - containerPort: 80