apiVersion: v1
kind: Service
metadata:
  name: hello-world-service2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello-world2
    spec:
      containers:
      - name: hello-world2
        image: $TAGGED_IMAGE_NAME
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URI
          value: "$MONGODB_URI"