apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - name: hello-world-nginx
        image: $TAGGED_IMAGE_NAME
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URI
          value: "$MONGODB_URI"